#!/bin/bash
# Auto-generated strategy: flowseal-alt43
# Source BAT: general (ALT5).bat
# Generated by auto-update-strategies workflow

config="--filter-l3=ipv4 --filter-tcp=443,2053,2083,2087,2096,8443, --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=syndata,multidisorder --new"
