#!/bin/bash
# Auto-generated strategy: flowseal-alt11
# Source BAT: general (ALT10).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fooling=ts --dpi-desync-fake-tls=$MODPATH/fake/tls_clienthello_4pda_to.bin --dpi-desync-fake-tls-mod=none --new"
