#!/bin/bash
# Auto-generated strategy: flowseal-alt104
# Source BAT: general (FAKE TLS AUTO).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake,multidisorder --dpi-desync-split-pos=1,midsld --dpi-desync-repeats=11 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=0x00000000 --dpi-desync-fake-tls=^! --dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com --new"
