#!/bin/bash
# Auto-generated strategy: flowseal-alt15
# Source BAT: general (ALT10).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=80,443, --ipset=$MODPATH/list/ipset-all.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fooling=ts --dpi-desync-fake-tls=^! --dpi-desync-fake-tls-mod=rnd,sni=www.google.com --dpi-desync-fake-tls=$MODPATH/fake/tls_clienthello_4pda_to.bin --dpi-desync-fake-tls-mod=none --new"
