#!/bin/bash
# Auto-generated strategy: flowseal-alt60
# Source BAT: general (ALT7).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=80,443, --ipset=$MODPATH/list/ipset-all.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=syndata --new"
