#!/bin/bash
# Auto-generated strategy: flowseal-alt130
# Source BAT: general.bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=80,443 --hostlist=$MODPATH/list/list-general.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=multisplit --dpi-desync-split-seqovl=568 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern=$MODPATH/fake/tls_clienthello_4pda_to.bin --new"
