#!/bin/bash
# Auto-generated strategy: flowseal-alt114
# Source BAT: general (SIMPLE FAKE ALT).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=80,443 --hostlist=$MODPATH/list/list-general.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=10000000 --dpi-desync-fake-tls=$MODPATH/fake/tls_clienthello_www_google_com.bin --new"
