#!/bin/bash
# Auto-generated strategy: flowseal-alt87
# Source BAT: general (FAKE TLS AUTO ALT2).bat
# Generated by auto-update-strategies workflow

config="--filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new"
