#!/bin/bash
# Auto-generated strategy: flowseal-alt64
# Source BAT: general (ALT8).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake --dpi-desync-fake-tls-mod=none --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=2 --new"
