#!/bin/bash
# Auto-generated strategy: flowseal-alt27
# Source BAT: general (ALT3).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-autottl=--dpi-desync-fooling=badseq --dpi-desync-repeats=8 --new"
