#!/bin/bash
# Auto-generated strategy: flowseal-alt57
# Source BAT: general (ALT7).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=443 --hostlist=$MODPATH/list/list-google.txt --ip-id=zero --dpi-desync=multisplit --dpi-desync-split-pos=2,sniext+1 --dpi-desync-split-seqovl=679 --dpi-desync-split-seqovl-pattern=$MODPATH/fake/tls_clienthello_www_google_com.bin --new"
