#!/bin/bash
# Auto-generated strategy: flowseal-alt105
# Source BAT: general (FAKE TLS AUTO).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=443 --hostlist=$MODPATH/list/list-google.txt --ip-id=zero --dpi-desync=fake,multidisorder --dpi-desync-split-pos=1,midsld --dpi-desync-repeats=11 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=0x00000000 --dpi-desync-fake-tls=^! --dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com --new"
