#!/bin/bash
# Auto-generated strategy: flowseal-alt73
# Source BAT: general (ALT9).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=443 --hostlist=$MODPATH/list/list-google.txt --ip-id=zero --dpi-desync=hostfakesplit --dpi-desync-repeats=4 --dpi-desync-fooling=ts --dpi-desync-hostfakesplit-mod=host=www.google.com --new"
