#!/bin/bash
# Auto-generated strategy: flowseal-alt59
# Source BAT: general (ALT7).bat
# Generated by auto-update-strategies workflow

config="--filter-udp=443 --ipset=$MODPATH/list/ipset-all.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=$MODPATH/fake/quic_initial_www_google_com.bin --new"
