#!/bin/bash
# Auto-generated strategy: flowseal-alt118
# Source BAT: general (SIMPLE FAKE).bat
# Generated by auto-update-strategies workflow

config="echo: --filter-udp=443 --hostlist=$MODPATH/list/list-general.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=$MODPATH/fake/quic_initial_www_google_com.bin --new"
