#!/bin/bash
# Auto-generated strategy: flowseal-alt133
# Source BAT: general.bat
# Generated by auto-update-strategies workflow

config="--filter-udp= --ipset=$MODPATH/list/ipset-all.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=$MODPATH/fake/quic_initial_www_google_com.bin --dpi-desync-cutoff=n2 --new"
