#!/bin/bash
# Auto-generated strategy: flowseal-alt23
# Source BAT: general (ALT2).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=80,443, --ipset=$MODPATH/list/ipset-all.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=multisplit --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern=$MODPATH/fake/tls_clienthello_www_google_com.bin --new"
