#!/bin/bash
# Auto-generated strategy: flowseal-alt128
# Source BAT: general.bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=multisplit --dpi-desync-split-seqovl=568 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern=$MODPATH/fake/tls_clienthello_4pda_to.bin --new"
