#!/bin/bash
# Auto-generated strategy: flowseal-alt120
# Source BAT: general (SIMPLE FAKE).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fooling=ts --dpi-desync-fake-tls=$MODPATH/fake/tls_clienthello_www_google_com.bin --new"
