#!/bin/bash
# Auto-generated strategy: flowseal-alt31
# Source BAT: general (ALT3).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=80,443, --ipset=$MODPATH/list/ipset-all.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-autottl=--dpi-desync-fooling=badseq --dpi-desync-repeats=8 --new"
