#!/bin/bash
# Auto-generated strategy: flowseal-alt49
# Source BAT: general (ALT6).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=443 --hostlist=$MODPATH/list/list-google.txt --ip-id=zero --dpi-desync=multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern=$MODPATH/fake/tls_clienthello_www_google_com.bin --new"
