#!/bin/bash
# Auto-generated strategy: flowseal-alt121
# Source BAT: general (SIMPLE FAKE).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=443 --hostlist=$MODPATH/list/list-google.txt --ip-id=zero --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fooling=ts --dpi-desync-fake-tls=$MODPATH/fake/tls_clienthello_www_google_com.bin --new"
