#!/bin/bash
# Auto-generated strategy: flowseal-alt47
# Source BAT: general (ALT6).bat
# Generated by auto-update-strategies workflow

config="--filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new"
