#!/bin/bash
# Auto-generated strategy: flowseal-alt65
# Source BAT: general (ALT8).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=443 --hostlist=$MODPATH/list/list-google.txt --ip-id=zero --dpi-desync=fake --dpi-desync-fake-tls-mod=none --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=2 --new"
