#!/bin/bash
# Auto-generated strategy: flowseal-alt7
# Source BAT: general (ALT).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=80,443, --ipset=$MODPATH/list/ipset-all.txt --hostlist-exclude=$MODPATH/list/list-exclude.txt --ipset-exclude=$MODPATH/list/ipset-exclude.txt --dpi-desync=fake,fakedsplit --dpi-desync-repeats=6 --dpi-desync-fooling=ts --dpi-desync-fakedsplit-pattern=0x00 --dpi-desync-fake-tls=$MODPATH/fake/tls_clienthello_www_google_com.bin --new"
