#!/bin/bash
# Auto-generated strategy: flowseal-alt28
# Source BAT: general (ALT3).bat
# Generated by auto-update-strategies workflow

config="--filter-tcp=443 --hostlist=$MODPATH/list/list-google.txt --ip-id=zero --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-autottl=--dpi-desync-fooling=badseq --dpi-desync-repeats=8 --new"
