#!/usr/bin/env python3
import re
import os
from pathlib import Path

def clean_and_join_lines(text):
    out = []
    for l in text.splitlines():
        s = l.strip()
        if not s:
            continue
        if s.startswith('::') or s.startswith('@echo') or s.startswith('chcp') or \
           s.startswith('cd ') or s.startswith('call ') or s.startswith('set ') or s.startswith('start '):
            continue
        s = s.rstrip('^').strip()
        out.append(s)
    return ' '.join(out)

def normalize_rule(rule):
    rule = re.sub(r'\s+', ' ', rule)
    rule = re.sub(r'--([a-z\-]+)\s+', r'--\1=', rule)
    rule = rule.replace('"', '')
    rule = rule.replace('\\', '/')
    rule = re.sub(r'%BIN%|"[^"]*\\bin\\', '$MODPATH/fake/', rule)
    rule = re.sub(r'%LISTS%|"[^"]*\\lists\\', '$MODPATH/list/', rule)
    rule = re.sub(r'%GameFilter%', '', rule)
    rule = re.sub(r'"[^"]*winws\.exe"\s*', '', rule)
    rule = re.sub(r'--wf-tcp[=\s]+[0-9,\-]+\s*', '', rule)
    rule = re.sub(r'--wf-udp[=\s]+[0-9,\-]+\s*', '', rule)
    return rule.strip()

def main():
    src = Path('upstream_bats')
    out_dir = Path('module/strategy')
    out_dir.mkdir(parents=True, exist_ok=True)
    seq = 1
    total = 0

    for bat in sorted(src.glob('*.bat')):
        try:
            text = bat.read_text(encoding='utf-8', errors='ignore')
            full = clean_and_join_lines(text)
            parts = [p.strip() for p in full.split('--new') if p.strip()]
            for p in parts:
                norm = normalize_rule(p)
                if not norm:
                    continue
                fname = out_dir / f'flowseal-alt{seq}.sh'
                header = f"""#!/bin/bash
# Auto-generated strategy: flowseal-alt{seq}
# Source BAT: {bat.name}
# Generated by auto-update-strategies workflow
"""
                body = f'config="{norm} --new"\n'
                fname.write_text(header + "\n" + body, encoding='utf-8')
                os.chmod(fname, 0o755)
                seq += 1
                total += 1
        except Exception as e:
            print(f"Error processing {bat}: {e}")

    print(f"Converted total: {total} files")

if __name__ == '__main__':
    main()
